### ISSUE TITLE
QR code library?

### ISSUE THREAD

**Issue by arsanyf** [devjos/ase_server#1]
Should we use a QR code library in the backend? Or is it better for the app to take the encoded value and generate the QR code locally?

**Comment by aicherst** [comment]
I think there are easy libraries to generate QR codes for both the server (Java) and the app (Android), but it would be easier and faster to just transmit a string rather than an image, so i would tend to generating them on the smartphones.

**Comment by JovanovicMarija** [comment]
Since image is needed only on Android (server and Raspberry Pi do not need image, just encoded value), i would also transmit only encoded value, and then create image out of it on Android. It also decreases internet usage.

**Comment by devjos** [comment]
+1 on doing it on android
